baseURL = "https://mike.foucault.io"
languageCode = "en-us"
title = "Mike-Anthony FOUCAULT"
theme = "introduction"
googleAnalytics = "UA-59779657-1"

[params]
    themeStyle                   = "light"                 # Choose "light" or "dark"
    favicon                      = "/img/fav.ico"          # Path to favicon file
    showRSSButton                = false                   # Show rss button in navigation
    fadeIn                       = true                    # Turn on/off the fade-in effect
    fadeInIndex                  = true                   # Turn on/off the fade-in effect on the index page even if fade-in was otherwise turned off
    dateFormat                   = "Jan 2, 2006"
    email                        = "contact@foucault.io"   # E-mail address for contact section
    # Configure the home page
    [params.home]
        introHeight              = "fullheight"            # Input either "medium" or "large" or "fullheight"
        showLatest               = true                    # Show latest blog post summary
        showAllPosts             = false                   # Set true to list all posts on home page, or set false to link to separate blog list page
        numberOfProjectsToShow   = 3                       # Maximum number of projects to show on home page. Unset or comment out to show all projects

        localTime                = false                    # Show your current local time in contact section
        timeZone                 = "Europe/Paris"   # Your timezone as in the TZ* column of this list: https://en.wikipedia.org/wiki/List_of_tz_database_time_zones
        timeFormat               = "h:mm A"                # https://momentjs.com/docs/#/displaying/format/
    [params.projects]
        useTwoColumns            = true                   # Use a layout with two columns instead of three
    # Share buttons on blog post pages
    [params.share]
        twitter                  = true
        facebook                 = false
        googlePlus               = false
        pinterest                = false
    # Social icons appear in introduction and contact section. Add as many more as you like.
    # Icon pack "fab" includes social network icons, see: https://fontawesome.com/icons?d=gallery&s=brands&m=free
    # Icon pack "fas" includes solid style icons, see: https://fontawesome.com/icons?d=gallery&s=solid&m=free
    [[params.social]]
        url = "https://github.com/mike-foucault"  # For a direct email link, use "mailto:test@example.org".
        icon = "github" # icon name without the 'fa-'
        icon_pack = "fab"
    [[params.social]]
        url   = "https://twitter.com/m_a_foucault/"
        icon  = "twitter" # icon name without the 'fa-'
        icon_pack = "fab"
    [[params.social]]
        url   = "https://www.linkedin.com/in/foucault/"
        icon  = "linkedin-in" # icon name without the 'fa-'
        icon_pack = "fab"
    [[params.social]]
        url = "mailto:contact@foucault.io"  # For a direct email link, use "mailto:test@example.org".
        icon = "paper-plane" # icon name without the 'fa-'
        icon_pack = "fas"

# We only use tag as a taxonomies
# You can add more by yourself
[taxonomies]
  tag = "tags"
